config/routes.rb
Rails.application.routes.draw do
    get "produtos/busca", to: "produtos#busca", as: :busca_produto
    resources :produtos, only: [:new, :create, :destroy]
    root to: "produtos#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/produto.rb
class Produto < ApplicationRecord
    validates :preco, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/produtos_controller.rb
class ProdutosController < ApplicationController

    def index
        @produtos = Produto.order :nome
        @produto_desconto = Produto.order(:preco).limit 1
    end    

    def create
        valores = params.require(:produto).permit(:nome,
        :descricao, :preco, :quantidade)
        produto = Produto.new valores
        if produto.save
            redirect_to root_url
        else
            render :new
        end
    end

    def destroy
        id = params[:id]
        Produto.destroy id
        redirect_to root_url
    end

    def busca
        @nome = params[:nome]
        @produtos = Produto.where "nome like ?", "%#{@nome}%"
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Loja do Giovane</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" 
    integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous"> -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootswatch/4.5.2/lux/bootstrap.min.css" 
    integrity="sha384-9+PGKSqjRdkeAU7Eu4nkJU8RFaH8ace8HGXnkiKMP9I9Te0GJ4/km3L1Z8tXigpG" crossorigin="anonymous">
</head>

<body>
    <%# <nav class="navbar navbar-light bg-light">
        <a class="navbar-brand" href="/">Navbar</a>
        <a class="btn btn-primary" href="/produtos/new">Cadastrar Novo</a>
        <div class="form-group">
            <%= text_field_tag %>
            <%# <% end %>
            <%# <%= button_to "Buscar", nil, class:"btn btn-default" %>
            <%# <% end %> 
        <%# </div>  %>
      <%# </nav> %>
    <%# <br/> %> 
<%= nav_bar brand: "Loja", brand_link: root_url do %>
  <%= menu_group do %>
    <%= menu_item "Criar novo produto", new_produto_path, class:"btn btn-info" %>
  <% end %>
  <%= form_tag busca_produto_path,method: :get, class:"navbar-form nav-bar-right" do %>
    <div class="form-group row">
        <%= text_field_tag :nome, @nome, class:"form-control" %>
        <%= button_to "Buscar", nil, class:"btn btn-primary" %>
        <% end %>
    </div>
<% end %>
    <div class="container">
        <%= yield %>
    </div>
</body>
</html>

app/views/layouts/install.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Loja" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Loja</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Link1", "/path1"  %></li>
            <li><%= link_to "Link2", "/path2"  %></li>
            <li><%= link_to "Link3", "/path3"  %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-3">
          <div class="well sidebar-nav">
            <h3>Sidebar</h3>
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2021</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/produtos/busca.html.erb
<table class="table table-striped table-hover ">
        <thead class="thead-dark">
            <tr>
                <td>Nome</td>
                <td>Descrição</td>
                <td>Preço</td>
                <td>Quantidade</td>
                <td colspan="1">
            </tr>
        </thead>
        <tbody>
        <% @produtos.each do |produto| %>
            <tr>
                <td><%= produto.nome %></td>
                <td><%= produto.descricao %></td>
                <td><%= produto.preco %></td>
                <td><%= produto.quantidade %></td>
                <td><%= link_to "Alterar", produto, method: :delete, class:"btn btn-warning"  %> </td>
                <td><%= button_to "Remover", produto, method: :delete, class:"btn btn-danger", data: {confirm: "Tem certeza que deseja deletar #{produto.nome}?"} %></td>
            </tr>
            <% end %>
        </tbody>
    </table>

app/views/produtos/index.html.erb
<h1 class="my-3">Produtos</h1>
    <table class="table table-striped table-hover ">
        <thead class="thead-dark">
            <tr>
                <td>Nome</td>
                <td>Descrição</td>
                <td>Preço</td>
                <td>Quantidade</td>
                <td colspan="1">
            </tr>
        </thead>
        <tbody>
        <% @produtos.each do |produto| %>
            <tr>
                <td><%= produto.nome %></td>
                <td><%= produto.descricao %></td>
                <td><%= produto.preco %></td>
                <td><%= produto.quantidade %></td>
                <td><%= link_to "Alterar", produto, method: :delete, class:"btn btn-warning"  %> </td>
                <td><%= button_to "Remover", produto, method: :delete, class:"btn btn-danger", data: {confirm: "Tem certeza que deseja deletar #{produto.nome}?"} %></td>
            </tr>
            <% end %>
        </tbody>
    </table>
    <div class="alert alert-success" role="alert">
        <h3 class="alert-heading">Produto com desconto</h3>
    </div>
        <table class="table table-striped table-hover ">
        <thead class="thead-dark">
            <tr>
                <td>Nome</td>
                <td>Descrição</td>
                <td>Preço</td>
                <td>Quantidade</td>

            </tr>
        </thead>
        <tbody>
        <% @produto_desconto.each do |produto| %>

            <tr>
                <td><%= produto.nome %></td>
                <td><%= produto.descricao %></td>
                <td><%= produto.preco %></td>
                <td><%= produto.quantidade %></td>
            </tr>
            <% end %>
        </tbody>
    </table>

app/views/produtos/new.html.erb
    <%= form_for Produto.new do |form| %>
        <div class="row">
            <div class="col-sm-8">
                <div class="form-group">
                    <%= form.label :nome %>
                    <%= form.text_field :nome, class:"form-control" %>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-8">
                <div class="form-group">
                    <%= form.label :descricao %>
                    <%= form.text_area :descricao, class:"form-control", rows:4 %>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-2">
                <div class="form-group">
                    <%= form.label :preco %>
                    <%= form.number_field :preco, step:0.01, class:"form-control" %>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-2">
                <div class="form-group">
                    <%= form.label :quantidade %>
                    <%= form.number_field :quantidade, class:"form-control" %>
                </div>
            </div>
        </div>
    <%= form.submit "Criar",class:"btn btn-primary" %>
<% end %>